name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: self-hosted
    strategy:
      matrix:
        file:
          - smartbob.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.1
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.8.0
        with:
          yaml_file: ${{ matrix.file }}
