name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - smartbob.yaml
    steps:
      - name: Checkout Secrets repository
        uses: actions/checkout@v4
        with:
          repository: atc024/esphome-secrets 
          path: './secrets'
          
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Copy secrets file before build
        run: cp ./secrets/secrets.yaml .

      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.8.0
        with:
          yaml_file: ${{ matrix.file }}
