name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/esphome-publish.yml
    with:
      files: smartbob.yaml
      name: SmartBob Project
    secrets: inherit
